--------------------------------------------------------
-- Archivo creado  - martes-febrero-18-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STATUSES
--------------------------------------------------------

  CREATE TABLE "DIEIDVIAL"."STATUSES" 
   (	"ID" NUMBER(38,0), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"CREATED_AT" DATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSVIALIDAD" ;
REM INSERTING into DIEIDVIAL.STATUSES
SET DEFINE OFF;
Insert into DIEIDVIAL.STATUSES (ID,DESCRIPTION,CREATED_AT,UPDATED_AT) values (10000,'DETENIDO',to_date('02/09/13','DD/MM/RR'),to_date('02/09/13','DD/MM/RR'));
Insert into DIEIDVIAL.STATUSES (ID,DESCRIPTION,CREATED_AT,UPDATED_AT) values (10001,'VICTIMA',to_date('02/09/13','DD/MM/RR'),to_date('02/09/13','DD/MM/RR'));
Insert into DIEIDVIAL.STATUSES (ID,DESCRIPTION,CREATED_AT,UPDATED_AT) values (10002,'SOSPECHOSO',to_date('02/09/13','DD/MM/RR'),to_date('02/09/13','DD/MM/RR'));
Insert into DIEIDVIAL.STATUSES (ID,DESCRIPTION,CREATED_AT,UPDATED_AT) values (10040,'TESTIGO',to_date('27/12/13','DD/MM/RR'),to_date('27/12/13','DD/MM/RR'));
Insert into DIEIDVIAL.STATUSES (ID,DESCRIPTION,CREATED_AT,UPDATED_AT) values (10041,'SOLICITADO',to_date('27/12/13','DD/MM/RR'),to_date('27/12/13','DD/MM/RR'));
Insert into DIEIDVIAL.STATUSES (ID,DESCRIPTION,CREATED_AT,UPDATED_AT) values (10025,'DESCONOCIDO',to_date('02/12/13','DD/MM/RR'),to_date('02/12/13','DD/MM/RR'));
Insert into DIEIDVIAL.STATUSES (ID,DESCRIPTION,CREATED_AT,UPDATED_AT) values (10026,'IMPUTADO IDENTIFICADO',to_date('04/12/13','DD/MM/RR'),to_date('04/12/13','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index SYS_C0046642
--------------------------------------------------------

  CREATE UNIQUE INDEX "DIEIDVIAL"."SYS_C0046642" ON "DIEIDVIAL"."STATUSES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSVIALIDAD" ;
--------------------------------------------------------
--  Constraints for Table STATUSES
--------------------------------------------------------

  ALTER TABLE "DIEIDVIAL"."STATUSES" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "DIEIDVIAL"."STATUSES" MODIFY ("CREATED_AT" NOT NULL ENABLE);
 
  ALTER TABLE "DIEIDVIAL"."STATUSES" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
 
  ALTER TABLE "DIEIDVIAL"."STATUSES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATOSVIALIDAD"  ENABLE;
